
package gui;

import javax.swing.JOptionPane;

public class GuiMenuPrincipal extends javax.swing.JFrame {

    public GuiMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSaida = new javax.swing.JMenu();
        btnEntrada = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnInformacoes = new javax.swing.JMenu();
        btnInformacoesDaProva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(421, 535));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        btnSaida.setText("Arquivo");

        btnEntrada.setText("Movimentação");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        btnSaida.add(btnEntrada);

        btnUsuarios.setText("Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        btnSaida.add(btnUsuarios);

        jMenuBar1.add(btnSaida);

        jMenu2.setText("Relatórios");

        jMenuItem3.setText("Faturamento Diário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Faturamento Mensal");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        btnInformacoes.setText("Sobre");

        btnInformacoesDaProva.setText("Informações sobre a Prova");
        btnInformacoesDaProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacoesDaProvaActionPerformed(evt);
            }
        });
        btnInformacoes.add(btnInformacoesDaProva);

        jMenuBar1.add(btnInformacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnInformacoesDaProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacoesDaProvaActionPerformed
        // TODO add your handling code here:

            JOptionPane.showMessageDialog(null, "********************************************* AVALIAÇÃO N2 *********************************************\n" +
"Aluno: Caio Barros Cardoso\n" +
"Professor: Alan Carvalho Galante\n" +
"Disciplina: Programação de Computadores III\n" +
"------------------------------------------------------------------------------------------------------------\n" +
"PROPOSTA:\n\n" +
"De posse do seu problema, a seguir, faça o diagrama de classes, o diagrama de caso de uso e para\n" +
"cada caso de uso, o diagrama de sequencia e a implementação do programa.\n" +
"\n" +
"A implementação deve ser feita com interfaces swing com uma janela principal do tipo MDI e as\n" +
"demais telas como frame interno (acessado através de menus) e caixa de diálogo (para o caso do\n" +
"usuário não poder interagir com mais de uma tela).\n" +
"\n" +
"Os dados devem ser persistidos em XML através da biblioteca xstream em local a ser parametrizado\n" +
"pelo usuário. O parâmetro de local dos arquivos xml deve ser um arquivo texto junto ao programa.\n" +
"\n" +
"O programa deve ter uma tela de login e os usuários com suas senhas também devem ser gravados\n" +
"em XML.\n" +
"------------------------------------------------------------------------------------------------------------\n" +
"PROBLEMA:\n\n" +
"Bruno e seu pai compraram um terreno e inaugurarão um estacionamento.\n" +
"\n" +
"Para ajudar, a irmã de Bruno está desenvolvendo uma aplicação de controle de estacionamento.\n" +
"\n" +
"Quando o veículo entra no estacionamento, o atendente observa sua placa e a mesma é cadastrada,\n" +
"juntamente com o modelo do veículo e sua cor.\n" +
"\n" +
"A hora de entrada é gerada automaticamente, correspondendo ao momento do cadastramento da\n" +
"placa. Após estacionar o veículo, o cliente pega o ticket onde está impresso: o número da placa, o\n" +
"modelo do veículo, a cor, a data e a hora da entrada.\n" +
"\n" +
"Ao retomar ao estacionamento, o cliente entrega o ticket. O tempo de permanência é calculado.\n" +
"Considerando esse tempo de permanência, é aplicada a tabela de preços, sabendo-se que a tabela de\n" +
"sábado não é a mesma dos dias úteis e, às vezes, dependendo da época do ano, os donos lançam\n" +
"promoções durante os dias úteis. Veja exemplo das tabelas de preço:\n" +
"\n" +
"Segunda a Sexta: 1ª hora = R$ 2,00 e a partir da 2ª hora (inteiro ou fração) = + R$ 1,00\n" +
"\n" +
"Sábado Preço Único: R$ 3,00 \n" +
"\n" +
"Obs: Os donos precisam de consulta de faturamento diário e semanal.");
    }//GEN-LAST:event_btnInformacoesDaProvaActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        
// Instanciando a tela de Movimentação =========================================  

        GuiMovimentacao telaMovimentacao = new GuiMovimentacao();
        jDesktopPane1.add(telaMovimentacao);
        telaMovimentacao.setVisible(true);
        
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

// Instanciando em primeiro plano a tela de login ==============================

        GuiLogin telaPrincipal = new GuiLogin(this,true);
        telaPrincipal.setVisible(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed

// Instanciando a tela de Cadastro de Usuários =================================        
        
        GuiCadastroUsuario telaUsuario = new GuiCadastroUsuario();
        jDesktopPane1.add(telaUsuario);
        telaUsuario.setVisible(true);
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnEntrada;
    private javax.swing.JMenu btnInformacoes;
    private javax.swing.JMenuItem btnInformacoesDaProva;
    private javax.swing.JMenu btnSaida;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
